name: Test and Link ReleaseFrameworkIos

on: pull_request

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run Tests
        run: ./gradlew check

      - name: linkReleaseFrameworkIos
        run: ./gradlew build
