name: Test and Build

on: pull_request

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Gradle check
        run: ./gradlew check

      - name: Gradle build
        run: ./gradlew build
